name: CI

on:
  push:
    paths:
      - "Assets/**"
      - "Packages/**"
      - "ProjectSettings/**"
      - ".github/**"
  pull_request:
    paths:
      - "Assets/**"
      - "Packages/**"
      - "ProjectSettings/**"
      - ".github/**"

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  tests:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        unityVersion:
          - 2018.4.16f1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-

      - uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts

      - uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
  
  code-quality:
    runs-on: ubuntu-latest
    needs: [tests]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
 
  build:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Prepare Package
        run: |
          mkdir build
          find ./Assets/Plugins/ -name \*.meta > metaList

      - name: create-unitypackage
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: build/bones3.unitypackage
          include-files: metaList

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: unitypackage
          path: build/bones3.unitypackage
